name: Docker build and push

on:
    push:
        branches: [ "main" ]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Set up Node.js 22
                uses: actions/setup-node@v4
                with:
                    node-version: 22

            -   name: Install dependencies
                run: npm install

            -   name: Build Angular app
                run: npm run build

            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v3
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build and push Docker image
                uses: docker/build-push-action@v5.3.0
                with:
                    context: .
                    file: ./iac/Dockerfile
                    push: true
                    tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
